// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJKP4B9XBGelHEygVDI6isaJfRQ6G2Tpw',
    appId: '1:1042661219588:web:9dbb7255483c2f5eb28451',
    messagingSenderId: '1042661219588',
    projectId: 'futorna-reservation-app',
    authDomain: 'futorna-reservation-app.firebaseapp.com',
    storageBucket: 'futorna-reservation-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF58e58AhtnNO4MKuwlE2ChU_zyGTV68g',
    appId: '1:1042661219588:android:8c49421e623e8891b28451',
    messagingSenderId: '1042661219588',
    projectId: 'futorna-reservation-app',
    storageBucket: 'futorna-reservation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUXlapYnbp84KXdC6vsZhpRLhhc4ODBeo',
    appId: '1:1042661219588:ios:e4f3583eaed964dfb28451',
    messagingSenderId: '1042661219588',
    projectId: 'futorna-reservation-app',
    storageBucket: 'futorna-reservation-app.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReservationApp',
  );
}
